apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     info
        Daemon        off

    [INPUT]
        Name              tail
        Path              /var/log/containers/*shady-trader*.log
        Parser            docker
        Tag               shady-trader.*
        Refresh_Interval  5

    [FILTER]
        Name                kubernetes
        Match               shady-trader.*
        Kube_URL           https://kubernetes.default.svc:443
        Kube_CA_File       /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File    /var/run/secrets/kubernetes.io/serviceaccount/token

    [OUTPUT]
        Name  loki
        Match shady-trader.*
        Host  loki.monitoring.svc.cluster.local
        Port  3100
        Labels job=shady-trader,app=backend